Project/WebApi/Cliente_IT3/Controllers/RoleController.cs
using Cliente_IT3.Helpers;
using Cliente_IT3.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Cliente_IT3.ViewModels;

namespace Cliente_IT3.Controllers
{
    public class RoleController : Controller
    {
        // GET: Role
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var roles =
                JsonConvert.DeserializeObject<IEnumerable<RoleVM>>(content);

                return View(roles);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        // GET: Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleVM rvm)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string roleJSON = JsonConvert.SerializeObject(rvm);
                HttpContent content = new StringContent(roleJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response = await client.PostAsync("api/Role", content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        // GET: Role/Delete/5
        public async Task<ActionResult> Delete(String id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeleteConfirmed(id);
            return RedirectToAction("Index");
        }

        // POST: Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(String id)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                var response = await client.DeleteAsync("api/Role?name=" + id);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        public async Task<ActionResult> addRoleToUser()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Role");
            var roles = new List<RoleVM>();
            var users = new List<ApplicationUser>();
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                roles =
                JsonConvert.DeserializeObject<IEnumerable<RoleVM>>(content).ToList();

                HttpResponseMessage response2 = await client.GetAsync("api/User");
                if (response2.IsSuccessStatusCode)
                {
                    string content2 = await response2.Content.ReadAsStringAsync();
                    users =
                    JsonConvert.DeserializeObject<IEnumerable<ApplicationUser>>(content2).ToList();
                }
                else
                {
                    return Content("Ocorreu um erro: " + response2.StatusCode);
                }

            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }

            List<String> users2 = (from u in users select u.UserName).ToList();
            List<String> roles2 = (from r in roles select r.name).ToList();

            ViewBag.Roles = new SelectList(roles2);
            ViewBag.Users = new SelectList(users2);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> addRoleToUser(RoleVM role)
        {
            var client = WebApiHttpClient.GetClient();
            string roleJSON = JsonConvert.SerializeObject(role);
            HttpContent content = new StringContent(roleJSON,
            System.Text.Encoding.Unicode, "application/json");
            var response = await client.PutAsync("api/addRoleToUser",content);
            if (response.IsSuccessStatusCode)
            {
                HttpResponseMessage response2 = await client.GetAsync("api/Role");
                var roles2 = new List<RoleVM>();
                var users2 = new List<ApplicationUser>();
                if (response2.IsSuccessStatusCode)
                {

                    if (role.user.Equals(WebApiHttpClient.userLogged.UserName))
                    {
                        WebApiHttpClient.role.Add(role.name);
                    }

                    string content2 = await response2.Content.ReadAsStringAsync();
                    roles2 =
                    JsonConvert.DeserializeObject<IEnumerable<RoleVM>>(content2).ToList();

                    HttpResponseMessage response3 = await client.GetAsync("api/User");
                    if (response3.IsSuccessStatusCode)
                    {
                        string content3 = await response3.Content.ReadAsStringAsync();
                        users2 =
                        JsonConvert.DeserializeObject<IEnumerable<ApplicationUser>>(content3).ToList();
                    }
                    else
                    {
                        return Content("Ocorreu um erro: " + response2.StatusCode);
                    }

                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }

                List<String> users3 = (from u in users2 select u.UserName).ToList();
                List<String> roles3 = (from r in roles2 select r.name).ToList();

                ViewBag.Roles = new SelectList(roles3);
                ViewBag.Users = new SelectList(users3);

                return View("AddRoleToUser");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteRoleForUser(string userName, string roleName)
        {
            var client = WebApiHttpClient.GetClient();
            var response = await client.DeleteAsync("api/Role?userName=" + userName + "&roleName=" + roleName);

            if (response.IsSuccessStatusCode)
            {

                if (userName.Equals(WebApiHttpClient.userLogged.UserName))
                {
                    WebApiHttpClient.role.Remove(roleName);
                }

                HttpResponseMessage response2 = await client.GetAsync("api/Role");
                var roles2 = new List<RoleVM>();
                var users2 = new List<ApplicationUser>();
                if (response2.IsSuccessStatusCode)
                {
                    string content2 = await response2.Content.ReadAsStringAsync();
                    roles2 =
                    JsonConvert.DeserializeObject<IEnumerable<RoleVM>>(content2).ToList();

                    HttpResponseMessage response3 = await client.GetAsync("api/User");
                    if (response3.IsSuccessStatusCode)
                    {
                        string content3 = await response3.Content.ReadAsStringAsync();
                        users2 =
                        JsonConvert.DeserializeObject<IEnumerable<ApplicationUser>>(content3).ToList();
                    }
                    else
                    {
                        return Content("Ocorreu um erro: " + response2.StatusCode);
                    }

                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }

                List<String> users3 = (from u in users2 select u.UserName).ToList();
                List<String> roles3 = (from r in roles2 select r.name).ToList();

                ViewBag.Roles = new SelectList(roles3);
                ViewBag.Users = new SelectList(users3);

                return View("AddRoleToUser");
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> GetUserRoles(string userName)
        {
            var client = WebApiHttpClient.GetClient();
            var response = await client.GetAsync("api/Role?userName=" + userName);

            List<string> roles = new List<string>();

            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var role =
                JsonConvert.DeserializeObject<IEnumerable<RoleVM>>(content);

Project/WebApi/Cliente_IT3/Views/Role/AddRoleToUser.cshtml
@model Cliente_IT3.ViewModels.RoleVM

@{
    ViewBag.Title = "addRoleToUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="spacerBody">
    <p>&nbsp;</p>
    @Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Roles", "Index")

    <h2>Add role to user</h2>
    @using (Html.BeginForm("addRoleToUser", "Role"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="message-success">@ViewBag.ResultMessage</div>
        <p>
            Username : @Html.DropDownList("user", ViewBag.Users as SelectList)
            Role Name: @Html.DropDownList("name", ViewBag.Roles as SelectList)
        </p>

        <input type="submit" value="Save" />
    }

    <h2>Remove role from user</h2>
    @using (Html.BeginForm("DeleteRoleForUser", "Role"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>
            Username : @Html.DropDownList("UserName", ViewBag.Users as SelectList)
            Role Name: @Html.DropDownList("RoleName", ViewBag.Roles as SelectList)
        </p>

        <input type="submit" value="Delete this user from Role" />
    }

    <h2>List roles for user</h2>
    @using (Html.BeginForm("GetUserRoles", "Role"))
    {
        @Html.AntiForgeryToken()
        <p>
            Username : @Html.DropDownList("UserName", ViewBag.Users as SelectList)
            <input type="submit" value="Get Roles for this User" />
        </p>
    }

    @if (ViewBag.RolesForThisUser != null)
    {
        <text>
            <h3>Roles for this user </h3>
            <ol>
                @foreach (string s in ViewBag.RolesForThisUser)
                {
                    <li>@s</li>
                }
            </ol>
        </text>
    }




</div>

Project/WebApi/Cliente_IT3/Views/Role/Create.cshtml
@model Cliente_IT3.ViewModels.RoleVM

@{
    ViewBag.Title = "Create Role";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="spacerBody">
    <p>&nbsp;</p>
    @Html.ActionLink("Roles", "Index") | @Html.ActionLink("Add Role to User", "AddToUser")
    <h2>Role Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div>
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
       
        <input type="submit" value="Create" />
    }
</div>

Project/WebApi/Cliente_IT3/Views/Role/Index.cshtml
@model IEnumerable<Cliente_IT3.ViewModels.RoleVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>&nbsp;</p>
<div class="spacerBody">
    <p>&nbsp;</p>
    <h2>Role index</h2>

    <p>
        @Html.ActionLink("Create New Role", "Create")
    </p>
    <p>
        @Html.ActionLink("Add Role to User", "AddRoleToUser")
    </p>


    @foreach (var item in Model)
    {
        <p>
            @item.name
            <span onclick=" return confirm('Are you sure to delete?') ">
                <a href="/Role/Delete?Id=@item.name" class="delLink">Delete</a>
            </span>
        </p>
    }
</div>