Project/WebApi/Cliente_IT3/Controllers/AdViewModelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cliente_IT3.ViewModels;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using Cliente_IT3.Helpers;
using System.Net.Http;
using Newtonsoft.Json;

namespace Cliente_IT3.Controllers
{
    public class AdViewModelController : Controller
    {

        // GET: AdViewModel
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Ad");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var ads =
                JsonConvert.DeserializeObject<IEnumerable<AdVM>>(content);
                return View(ads);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        // GET: AdViewModel/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Ad/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var ad = JsonConvert.DeserializeObject<AdVM>(content);
                if (ad == null) return HttpNotFound();
                return View(ad);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }


        // GET: AdViewModel/Create
        public async Task<ActionResult> Create()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/AdType");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var adts =
                JsonConvert.DeserializeObject<IEnumerable<AdTypeVM>>(content);

                ViewBag.AdTypeID = new SelectList(adts, "AdTypeID", "Description");
            }

            var rts = new List<RealtyTypeVM>();

            HttpResponseMessage response2 = await client.GetAsync("api/RealtyType");
            if (response2.IsSuccessStatusCode)
            {
                string content2 = await response2.Content.ReadAsStringAsync();
                rts =
                JsonConvert.DeserializeObject<IEnumerable<RealtyTypeVM>>(content2).ToList();

                ViewBag.RealtyTypeID = new SelectList(rts, "RealtyTypeID", "Description");
            }

            if (rts.Count == 0)
            {
                TempData["erro"] = "Impossible to create Ad. No Realty Types created.";
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        // POST: AdViewModel/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AdVM ad)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string adJSON = JsonConvert.SerializeObject(ad);
                HttpContent content = new StringContent(adJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response = await client.PostAsync("api/Ad", content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        // GET: AdViewModel/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Ad/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var ad = JsonConvert.DeserializeObject<AdVM>(content);
                if (ad == null) return HttpNotFound();

                HttpResponseMessage response2 = await client.GetAsync("api/AdType");
                if (response2.IsSuccessStatusCode)
                {
                    string content2 = await response2.Content.ReadAsStringAsync();
                    var adts =
                    JsonConvert.DeserializeObject<IEnumerable<AdTypeVM>>(content2);

                    ViewBag.AdTypeID = new SelectList(adts, "AdTypeID", "Description");
                }

                HttpResponseMessage response3 = await client.GetAsync("api/RealtyType");
                if (response3.IsSuccessStatusCode)
                {
                    string content3 = await response3.Content.ReadAsStringAsync();
                    var rts =
                    JsonConvert.DeserializeObject<IEnumerable<RealtyTypeVM>>(content3);

                    ViewBag.RealtyTypeID = new SelectList(rts, "RealtyTypeID", "Description");
                }

                return View(ad);
            }
            return Content("Ocorreu um erro: " + response.StatusCode);
        }

        // POST: AdViewModel/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AdVM ad)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string adJSON = JsonConvert.SerializeObject(ad);
                HttpContent content = new StringContent(adJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response =
                await client.PutAsync("api/Ad/" + ad.AdID, content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }


        // GET: AdViewModel/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Ad/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var ad = JsonConvert.DeserializeObject<AdVM>(content);
                if (ad == null) return HttpNotFound();
                return View(ad);
            }
            return Content("Ocorreu um erro: " + response.StatusCode);
        }

        // POST: AdViewModel/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                var response = await client.DeleteAsync("api/Ad/" + id);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

    }
}

Project/WebApi/Cliente_IT3/Controllers/AvailibilityController.cs
using Cliente_IT3.Helpers;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Cliente_IT3.ViewModels;
using System.Net;

namespace Cliente_IT3.Controllers
{
    public class AvailibilityController : Controller
    {
        // GET: Availibility
        public async Task<ActionResult> Index()
        {
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Availability");
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var availability =
                JsonConvert.DeserializeObject<IEnumerable<AvailabilityVM>>(content);
                return View(availability);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        // GET: Availibility/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Availability/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var availibility = JsonConvert.DeserializeObject<AvailabilityVM>(content);
                if (availibility == null) return HttpNotFound();
                return View(availibility);
            }
            else
            {
                return Content("Ocorreu um erro: " + response.StatusCode);
            }
        }

        // GET: Availibility/Create
        public async Task<ActionResult> Create(int? id)
        {
            var client = WebApiHttpClient.GetClient();
           var availibility = new AvailabilityVM();
            HttpResponseMessage response2 = await client.GetAsync("api/ad/"+id);
            if (response2.IsSuccessStatusCode)
            {
                string content2 = await response2.Content.ReadAsStringAsync();
               var ad = JsonConvert.DeserializeObject<AdVM>(content2);
                availibility.realtyID = ad.RealtyID;
                availibility.User = WebApiHttpClient.userLogged.UserName;

            }



            return View(availibility);
        }

        // POST: Availibility/Create
        [HttpPost]
        public async Task<ActionResult> Create(AvailabilityVM Availability)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string adJSON = JsonConvert.SerializeObject(Availability);
                HttpContent content = new StringContent(adJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response = await client.PostAsync("api/Availability", content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("index", "AdViewModel", new { area = "" });
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        // GET: Availibility/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Availability/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var availability = JsonConvert.DeserializeObject<AvailabilityVM>(content);
                if (availability == null) return HttpNotFound();
                
                return View(availability);
            }
            return Content("Ocorreu um erro: " + response.StatusCode);
        }

        // POST: Availibility/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AvailabilityVM avai)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                string adJSON = JsonConvert.SerializeObject(avai);
                HttpContent content = new StringContent(adJSON,
                System.Text.Encoding.Unicode, "application/json");
                var response =
                await client.PutAsync("api/Availability/" + avai.ID, content);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }

        // GET: Availibility/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var client = WebApiHttpClient.GetClient();
            HttpResponseMessage response = await client.GetAsync("api/Availability/" + id);
            if (response.IsSuccessStatusCode)
            {
                string content = await response.Content.ReadAsStringAsync();
                var avai = JsonConvert.DeserializeObject<AvailabilityVM>(content);
                if (avai == null) return HttpNotFound();
                return View(avai);
            }
            return Content("Ocorreu um erro: " + response.StatusCode);
        }

        // POST: Availibility/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var client = WebApiHttpClient.GetClient();
                var response = await client.DeleteAsync("api/Availability/" + id);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return Content("Ocorreu um erro: " + response.StatusCode);
                }
            }
            catch
            {
                return Content("Ocorreu um erro.");
            }
        }
    }
}

Project/WebApi/Cliente_IT3/Views/AdViewModel/Create.cshtml
@model Cliente_IT3.ViewModels.AdVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ad</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdTypeID, "AdType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AdTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RealtyTypeID, "RealtyType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RealtyTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RealtyTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Altitude, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Altitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Altitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo[0], "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo[0], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo[0], "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo[1], "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo[1], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo[1], "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo[2],  "Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo[2], new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photo[2], "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project/WebApi/Cliente_IT3/Views/AdViewModel/Delete.cshtml
@model Cliente_IT3.ViewModels.AdVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RealtyTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RealtyTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Altitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Altitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        @if (Model.Photo.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Photo)
            </dt>

            for (int i = 0; i < Model.Photo.Count; i++)
            {
                if (Model.Photo[i] != null)
                {
                    <td>
                        <img src="@Model.Photo[i]" alt="image" width="100px" height="100px" />
                    </td>

                }
            }
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/WebApi/Cliente_IT3/Views/AdViewModel/Details.cshtml
@using Cliente_IT3.Helpers
@model Cliente_IT3.ViewModels.AdVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RealtyTypeDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RealtyTypeDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndHour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndHour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Altitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Altitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        @if (Model.Photo.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Photo)
            </dt>
            for (int i = 0; i < Model.Photo.Count; i++)
            {
                if (Model.Photo[i] != null)
                {
                    <td>
                        <img src="@Model.Photo[i]" alt="image" width="100px" height="100px" />
                    </td>

                }
            }
        }

    </dl>
</div>
@if (Model.User.Equals(WebApiHttpClient.userLogged.UserName))
{
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AdID }) |
    @Html.ActionLink("Back to List", "Index")

</p>
}
else
{
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Project/WebApi/Cliente_IT3/Views/AdViewModel/Index.cshtml
@using Cliente_IT3.Helpers
@model IEnumerable<Cliente_IT3.ViewModels.AdVM>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Ad", "Create")
</p>
<table class="table">
    <tr>
        @if (TempData["erro"] != null)
        {
            <span style="color:Red;">  @TempData["erro"] </span>
        }
        <th>
            @Html.DisplayNameFor(model => model.AdTypeDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RealtyTypeDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AdTypeDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RealtyTypeDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>

        @if (item.Photo.Count > 0)
        {
            if (item.Photo[0] != null)
            {
                <td>
                    <img src="@item.Photo[0]" alt="image" width="50px" height="50px" />
                </td>
            }
            else
            {
                <td></td>
            }
        }
        else
        {
            <td></td>
        }

        @if (item.isProprietary(WebApiHttpClient.userLogged.UserName))
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.AdID }) |
                @Html.ActionLink("Details", "Details", new { id = item.AdID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.AdID }) |
                @Html.ActionLink("Visit", "Create", "Availibility", new { id = item.AdID },null)
            </td>
        }
        else
        {
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.AdID }) |
                    @Html.ActionLink("Visit", "Create", "Availibility", new { id = item.AdID },null)
                </td>
        }
    </tr>
}

</table>